### ISSUE TITLE
viscm is incompatible with mpl2.0b3/numpy1.11.1

### ISSUE THREAD

**Issue by anntzer** [matplotlib/viscm#18]
`view` seems to break on a numpy change.

```
$ python -mviscm view magma
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 182, in __draw_idle_agg
    FigureCanvasAgg.draw(self)
  File "/usr/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 463, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/matplotlib/figure.py", line 1129, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/usr/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2375, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/usr/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/matplotlib/image.py", line 496, in draw
    renderer.draw_image(gc, l, b, im)
TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'
```

`edit` seems to break on a mpl change.

```
$ python -mviscm edit magma
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/viscm/__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "/usr/lib/python3.5/site-packages/viscm/gui.py", line 898, in main
    v = viscm_editor(uniform_space=uniform_space, **params)
  File "/usr/lib/python3.5/site-packages/viscm/gui.py", line 456, in __init__
    axes = _viscm_editor_axes()
  File "/usr/lib/python3.5/site-packages/viscm/gui.py", line 441, in _viscm_editor_axes
    height_ratios=[6, 1])
  File "/usr/lib/python3.5/site-packages/matplotlib/gridspec.py", line 217, in __init__
    height_ratios=height_ratios)
  File "/usr/lib/python3.5/site-packages/matplotlib/gridspec.py", line 47, in __init__
    self.set_height_ratios(height_ratios)
  File "/usr/lib/python3.5/site-packages/matplotlib/gridspec.py", line 76, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid
```

**Comment by njsmith** [comment]
Seems to work for me with current viscm master and matplotlib 2.0.0rc1
