### ISSUE TITLE
package fails to run on mpl 2.0.0rc2

### ISSUE THREAD

**Issue by akhmerov** [matplotlib/viscm#24]
```
$ python3 -m viscm
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/viscm/__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 898, in main
    v = viscm_editor(uniform_space=uniform_space, **params)
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 456, in __init__
    axes = _viscm_editor_axes()
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 441, in _viscm_editor_axes
    height_ratios=[6, 1])
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/gridspec.py", line 217, in __init__
    height_ratios=height_ratios)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/gridspec.py", line 47, in __init__
    self.set_height_ratios(height_ratios)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/gridspec.py", line 76, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid

$ ipython -c "import matplotlib; matplotlib.__version__"
Out[1]: '2.0.0rc2'
```

**Comment by njsmith** [comment]
Are you using the version from pypi ("pip install viscm")? If so this is
already fixed in master (but master is currently in a bit of flux, and
doesn't generate standard save files).

**Comment by akhmerov** [comment]
Indeed, I can confirm that the issue doesn't occur on master, thanks.
