### ISSUE TITLE
GridSpec error: Expected the given number of height ratios to match the number of rows of the grid

### ISSUE THREAD

**Issue by aldenks** [matplotlib/viscm#26]
Hello, I am trying to run viscm with `python -m viscm edit` and encountering the following error. I'm on OSX with python 3.5.2 and have viscm 0.7 installed with `pip install viscm`.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alden/code/upstream/colormaps/.venv/lib/python3.5/site-packages/viscm/__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "/Users/alden/code/upstream/colormaps/.venv/lib/python3.5/site-packages/viscm/gui.py", line 898, in main
    v = viscm_editor(uniform_space=uniform_space, **params)
  File "/Users/alden/code/upstream/colormaps/.venv/lib/python3.5/site-packages/viscm/gui.py", line 456, in __init__
    axes = _viscm_editor_axes()
  File "/Users/alden/code/upstream/colormaps/.venv/lib/python3.5/site-packages/viscm/gui.py", line 441, in _viscm_editor_axes
    height_ratios=[6, 1])
  File "/Users/alden/code/upstream/colormaps/.venv/lib/python3.5/site-packages/matplotlib/gridspec.py", line 217, in __init__
    height_ratios=height_ratios)
  File "/Users/alden/code/upstream/colormaps/.venv/lib/python3.5/site-packages/matplotlib/gridspec.py", line 47, in __init__
    self.set_height_ratios(height_ratios)
  File "/Users/alden/code/upstream/colormaps/.venv/lib/python3.5/site-packages/matplotlib/gridspec.py", line 76, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid
```

Any thing I can do to fix it? Thank you!

**Comment by bewantbe** [comment]
Hit the same problem, the related code is (in gui.py):
```
def _viscm_editor_axes():
    grid = GridSpec(1, 2,
                    width_ratios=[5, 1],
                    height_ratios=[6, 1])
```
The "height_ratios" specification is not very meaningful since it is 1x2 grid.

Without understanding the resting code, my quick fix is to make it a 2x2 grid:

``` # gui.py
def _viscm_editor_axes():
    grid = GridSpec(2, 2,
                    width_ratios=[5, 1],
                    height_ratios=[6, 1])
```

**Comment by stefanv** [comment]
Fixed in latest version; please install from git.
