### ISSUE TITLE
No display using conda Python 3.6.0 and Numpy 1.12.0

### ISSUE THREAD

**Issue by wafels** [matplotlib/viscm#29]
I am running the conda version of Python 3.6.0 and its attendant scientific packages, including the latest version of Numpy that comes with Python 3.6.0. I installed viscm via pip.  On trying to view a matplotlib colormap a matplotlib window pops up but then I get an error. Any recommendation on how to get around this? Thanks!  I really want to adapt this tool to load in some IDL colortables that my particular field of study uses.

$ python -m viscm view jet
Traceback (most recent call last):
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 136, in _draw
    self.figure.draw(renderer)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/ireland/anaconda/lib/python3.6/site-packages/matplotlib/image.py", line 497, in draw
    renderer.draw_image(gc, l, b, im)
TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'

**Comment by bewantbe** [comment]
Try use a more recent version of viscm (https://github.com/matplotlib/viscm). This bug is fix by https://github.com/matplotlib/viscm/commit/6d87f132dd9cbcac1dc7c1c0e4e765c62165f548

**Comment by wafels** [comment]
Thanks, that worked.
