### ISSUE TITLE
TypeError when trying to use package

### ISSUE THREAD

**Issue by vbollen** [matplotlib/viscm#30]
Hello, I'm having issues running this package. It used to work before, but it has been a while since I have used it (probably before Matplotlib 2.0 release), and it get the following exception when I try to run the example:

`C:\Users\vikto_000>python -m viscm view jet
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 197, in __draw_idle_agg FigureCanvasAgg.draw(self)
  File "C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 464, in draw self.figure.draw(self.renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\figure.py", line 1143, in draw renderer, self, dsu, self.suppressComposite)
  File "C:\Anaconda3\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images a.draw(renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 2409, in draw mimage._draw_list_compositing_images(renderer, self, dsu)
  File "C:\Anaconda3\lib\site-packages\matplotlib\image.py", line 139, in _draw_list_compositing_images a.draw(renderer)
  File "C:\Anaconda3\lib\site-packages\matplotlib\artist.py", line 63, in draw_wrapper draw(artist, renderer, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\matplotlib\image.py", line 497, in draw renderer.draw_image(gc, l, b, im)

TypeError: Cannot cast array data from dtype('float64') to dtype('uint8') according to the rule 'safe'`

I am using the latest version of viscm and matplotlib.

**Comment by tacaswell** [comment]
I believe this is fixed by https://github.com/matplotlib/viscm/pull/20

**Comment by epipping** [comment]
For now,
```python
pip uninstall matplotlib
pip install matplotlib==1.5.3
```
can serve as workaround.

**Comment by sammosummo** [comment]
I encountered this too.

I think the following is preferable:

```pip install --upgrade git+git://github.com/matplotlib/viscm```

I don't really want to downgrade `matplotlib`.

**Comment by bendichter** [comment]
that caused a new error. Is it a C error? I am not familiar.

```
pip install --upgrade git+git://github.com/matplotlib/viscm
python -m viscm view jet


2017-08-09 13:39:13.320 python[61924:12827861] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSApplication _setup:]: unrecognized selector sent to instance 0x7fd28b5d0f50'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff975b14f2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9d12bf7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9761b1ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff97521571 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff975210f8 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x0000000109224948 TkpInit + 476
	6   Tk                                  0x000000010919fa6e Tk_Init + 1799
	7   _tkinter.cpython-36m-darwin.so      0x000000010907cda4 Tcl_AppInit + 84
	8   _tkinter.cpython-36m-darwin.so      0x000000010907ca7b _tkinter_create + 1115
	9   libpython3.6m.dylib                 0x000000010481da81 _PyCFunction_FastCallDict + 497
	10  libpython3.6m.dylib                 0x000000010489f787 call_function + 439
	11  libpython3.6m.dylib                 0x000000010489bf62 _PyEval_EvalFrameDefault + 27346
	12  libpython3.6m.dylib                 0x00000001048a01ef _PyEval_EvalCodeWithName + 2447
	13  libpython3.6m.dylib                 0x00000001048a0d92 _PyFunction_FastCallDict + 738
	14  libpython3.6m.dylib                 0x00000001047d5677 _PyObject_FastCallDict + 247
	15  libpython3.6m.dylib                 0x00000001047d5795 _PyObject_Call_Prepend + 149
	16  libpython3.6m.dylib                 0x00000001047d54b0 PyObject_Call + 96
	17  libpython3.6m.dylib                 0x0000000104835aed slot_tp_init + 125
	18  libpython3.6m.dylib                 0x0000000104831e29 type_call + 313
	19  libpython3.6m.dylib                 0x00000001047d5645 _PyObject_FastCallDict + 197
	20  libpython3.6m.dylib                 0x000000010489f688 call_function + 184
	21  libpython3.6m.dylib                 0x000000010489bf62 _PyEval_EvalFrameDefault + 27346
	22  libpython3.6m.dylib                 0x00000001048a09ed fast_function + 381
	23  libpython3.6m.dylib                 0x000000010489f761 call_function + 401
	24  libpython3.6m.dylib                 0x000000010489bf62 _PyEval_EvalFrameDefault + 27346
	25  libpython3.6m.dylib                 0x00000001048a01ef _PyEval_EvalCodeWithName + 2447
	26  libpython3.6m.dylib                 0x0000000104895444 PyEval_EvalCodeEx + 100
	27  libpython3.6m.dylib                 0x00000001047fe5ed function_call + 381
	28  libpython3.6m.dylib                 0x00000001047d54b0 PyObject_Call + 96
	29  libpython3.6m.dylib                 0x000000010489c245 _PyEval_EvalFrameDefault + 28085
	30  libpython3.6m.dylib                 0x00000001048a01ef _PyEval_EvalCodeWithName + 2447
	31  libpython3.6m.dylib                 0x00000001048a0a91 fast_function + 545
	32  libpython3.6m.dylib                 0x000000010489f761 call_function + 401
	33  libpython3.6m.dylib                 0x000000010489bf62 _PyEval_EvalFrameDefault + 27346
	34  libpython3.6m.dylib                 0x00000001048a09ed fast_function + 381
	35  libpython3.6m.dylib                 0x000000010489f761 call_function + 401
	36  libpython3.6m.dylib                 0x000000010489bf62 _PyEval_EvalFrameDefault + 27346
	37  libpython3.6m.dylib                 0x00000001048a01ef _PyEval_EvalCodeWithName + 2447
	38  libpython3.6m.dylib                 0x00000001048953d4 PyEval_EvalCode + 100
	39  libpython3.6m.dylib                 0x0000000104892b54 builtin_exec + 548
	40  libpython3.6m.dylib                 0x000000010481da81 _PyCFunction_FastCallDict + 497
	41  libpython3.6m.dylib                 0x000000010489f787 call_function + 439
	42  libpython3.6m.dylib                 0x000000010489bf62 _PyEval_EvalFrameDefault + 27346
	43  libpython3.6m.dylib                 0x00000001048a01ef _PyEval_EvalCodeWithName + 2447
	44  libpython3.6m.dylib                 0x00000001048a0a91 fast_function + 545
	45  libpython3.6m.dylib                 0x000000010489f761 call_function + 401
	46  libpython3.6m.dylib                 0x000000010489bf62 _PyEval_EvalFrameDefault + 27346
	47  libpython3.6m.dylib                 0x00000001048a01ef _PyEval_EvalCodeWithName + 2447
	48  libpython3.6m.dylib                 0x0000000104895444 PyEval_EvalCodeEx + 100
	49  libpython3.6m.dylib                 0x00000001047fe5ed function_call + 381
	50  libpython3.6m.dylib                 0x00000001047d54b0 PyObject_Call + 96
	51  libpython3.6m.dylib                 0x00000001048e39e3 RunModule + 147
	52  libpython3.6m.dylib                 0x00000001048e337b Py_Main + 2619
	53  python                              0x00000001047c5df8 main + 232
	54  libdyld.dylib                       0x00007fff87e195ad start + 1
	55  ???                                 0x0000000000000005 0x0 + 5
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by bendichter** [comment]
downgrading mpl worked

**Comment by stefanv** [comment]
This should be fixed; please install latest version from git.
