### ISSUE TITLE
TypeError when trying to save a file

### ISSUE THREAD

**Issue by akhmerov** [matplotlib/viscm#31]
It appears, that some modifications were only performed partially. When trying to save files, I see the following error:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 1315, in save
    self.viscm_editor.save_colormap(fileName)
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 599, in save_colormap
    with open(filepath, 'w') as f:
TypeError: invalid file: ('.../test.jscm', 'JSCM Files (*.jscm)')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 1315, in save
    self.viscm_editor.save_colormap(fileName)
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 599, in save_colormap
    with open(filepath, 'w') as f:
TypeError: invalid file: ('', '')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 1303, in export
    self.viscm_editor.export_py(fileName)
  File "/usr/local/lib/python3.5/dist-packages/viscm/gui.py", line 648, in export_py
    with open(filepath, 'w') as f:
TypeError: invalid file: ('.../cm.py', '.py (*.py)')
```
I believe only the first element of corresponding tuples should be passed to `open`.

**Comment by njsmith** [comment]
This is some annoying cross version inconsistency in qt...

**Comment by tacaswell** [comment]
I think https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_compat.py#L151 is to shim around this.

**Comment by akhmerov** [comment]
Should this issue then disappear on mpl master? I've observed it with 2.0.0.

**Comment by tacaswell** [comment]
No, I think you viscm might need to use this shim

**Comment by stefanv** [comment]
This should be fixed; please install latest from git.
