### ISSUE TITLE
set_height_ratios error

### ISSUE THREAD

**Issue by neilpanchal** [matplotlib/viscm#35]
Hello,

When I try to run `python -m viscm edit`, I am getting the following error (on anaconda3 for python 3.6):

```
★ ~ / ➞  python -m viscm edit
Traceback (most recent call last):
  File "/Users/neil/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/neil/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/neil/miniconda3/lib/python3.6/site-packages/viscm/__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "/Users/neil/miniconda3/lib/python3.6/site-packages/viscm/gui.py", line 898, in main
    v = viscm_editor(uniform_space=uniform_space, **params)
  File "/Users/neil/miniconda3/lib/python3.6/site-packages/viscm/gui.py", line 456, in __init__
    axes = _viscm_editor_axes()
  File "/Users/neil/miniconda3/lib/python3.6/site-packages/viscm/gui.py", line 441, in _viscm_editor_axes
    height_ratios=[6, 1])
  File "/Users/neil/miniconda3/lib/python3.6/site-packages/matplotlib/gridspec.py", line 203, in __init__
    height_ratios=height_ratios)
  File "/Users/neil/miniconda3/lib/python3.6/site-packages/matplotlib/gridspec.py", line 45, in __init__
    self.set_height_ratios(height_ratios)
  File "/Users/neil/miniconda3/lib/python3.6/site-packages/matplotlib/gridspec.py", line 74, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid
```

**Comment by chrisgervang** [comment]
I'm getting this error too, and I'm in python 2.7 using a virtual env on OSX.

**Comment by nicoguaro** [comment]
I have the same error in Python 2.7 and Linux Mint.

When I try to run ``python -m viscm edit``, I get

    Traceback (most recent call last):
      File "/home/nguarinz/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/home/nguarinz/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/nguarinz/anaconda2/lib/python2.7/site-packages/viscm/__main__.py", line 8, in <module>
        main(sys.argv[1:])
      File "/home/nguarinz/anaconda2/lib/python2.7/site-packages/viscm/gui.py", line 898, in main
        v = viscm_editor(uniform_space=uniform_space, **params)
      File "/home/nguarinz/anaconda2/lib/python2.7/site-packages/viscm/gui.py", line 456, in __init__
        axes = _viscm_editor_axes()
      File "/home/nguarinz/anaconda2/lib/python2.7/site-packages/viscm/gui.py", line 441, in _viscm_editor_axes
        height_ratios=[6, 1])
      File "/home/nguarinz/anaconda2/lib/python2.7/site-packages/matplotlib/gridspec.py", line 203, in __init__
        height_ratios=height_ratios)
      File "/home/nguarinz/anaconda2/lib/python2.7/site-packages/matplotlib/gridspec.py", line 45, in __init__
        self.set_height_ratios(height_ratios)
      File "/home/nguarinz/anaconda2/lib/python2.7/site-packages/matplotlib/gridspec.py", line 74, in set_height_ratios
        raise ValueError('Expected the given number of height ratios to '
    ValueError: Expected the given number of height ratios to match the number of rows of the grid

**Comment by stefanv** [comment]
Fixed in latest git; please install from there.
