### ISSUE TITLE
TypeError when saving

### ISSUE THREAD

**Issue by drammock** [matplotlib/viscm#38]
I get a different `TypeError` when saving than the one mentioned in #31:

```
$ python -m viscm edit
/opt/miniconda3/envs/three/lib/python3.6/site-packages/viscm/gui.py:835: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  self.ax.set_axis_bgcolor(self.bgcolors[self.bg])
/opt/miniconda3/envs/three/lib/python3.6/site-packages/numpy/core/_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
Traceback (most recent call last):
  File "/opt/miniconda3/envs/three/lib/python3.6/site-packages/viscm/gui.py", line 1311, in save
    self.viscm_editor.save_colormap(fileName)
  File "/opt/miniconda3/envs/three/lib/python3.6/site-packages/viscm/gui.py", line 599, in save_colormap
    with open(filepath, 'w') as f:
TypeError: expected str, bytes or os.PathLike object, not tuple
Aborted (core dumped)
$ python -c "import matplotlib; print(matplotlib.__version__)"
2.1.2
$ python -c "import numpy; print(numpy.__version__)"
1.14.0
```
just before this I ran `pip install --upgrade git+git://github.com/matplotlib/viscm.git` to make sure I'm on most current version.

**Comment by stefanv** [comment]
This seems to be fixed; please re-open if that's not the case.

**Comment by drammock** [comment]
confirmed, works now, thanks.
