### ISSUE TITLE
vism edit crash

### ISSUE THREAD

**Issue by polwel** [matplotlib/viscm#40]
I fail to start viscm edit with MPL 2.2.2.

```
Traceback (most recent call last):
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\site-packages\viscm\__main__.py", line 8, in <module>
    main(sys.argv[1:])
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\site-packages\viscm\gui.py", line 898, in main
    v = viscm_editor(uniform_space=uniform_space, **params)
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\site-packages\viscm\gui.py", line 456, in __init__
    axes = _viscm_editor_axes()
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\site-packages\viscm\gui.py", line 441, in _viscm_editor_axes
    height_ratios=[6, 1])
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\site-packages\matplotlib\gridspec.py", line 206, in __init__
    height_ratios=height_ratios)
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\site-packages\matplotlib\gridspec.py", line 48, in __init__
    self.set_height_ratios(height_ratios)
  File "C:\Users\welterp\AppData\Local\Continuum\miniconda3\envs\qs3\lib\site-packages\matplotlib\gridspec.py", line 77, in set_height_ratios
    raise ValueError('Expected the given number of height ratios to '
ValueError: Expected the given number of height ratios to match the number of rows of the grid
```

**Comment by marcandrevigneault** [comment]
Same for me

**Comment by stefanv** [comment]
This seems to be fixed with the latest version.  Please re-open if that's not the case.
