### ISSUE TITLE
Editor misbehavior with `option_d.py`

### ISSUE THREAD

**Issue by mfisher87** [matplotlib/viscm#76]
When loading `option_d.py` (as in the README), the colormap is mostly out of gamut (is that the right term?).

![image](https://github.com/matplotlib/viscm/assets/3608264/82578bb5-7b78-4657-afbd-dc6aaa98fbd5)

When using "Load in viewer":

```
Traceback (most recent call last):
  File "/home/robatt/Projects/_external/viscm/viscm/gui.py", line 1319, in loadviewer
    v = viscm(cm, name=self.viscm_editor.name, figure=newfig)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robatt/Projects/_external/viscm/viscm/gui.py", line 265, in __init__
    Jpapbp = self._sRGB1_to_uniform(RGB)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robatt/.local/share/miniconda3/envs/viscm/lib/python3.11/site-packages/colorspacious/transform_graph.py", line 581, in __call__
    x = transform(x, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robatt/.local/share/miniconda3/envs/viscm/lib/python3.11/site-packages/colorspacious/conversion.py", line 86, in _XYZ100_to_CIECAM02
    return ciecam02_space.XYZ100_to_CIECAM02(XYZ100)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/robatt/.local/share/miniconda3/envs/viscm/lib/python3.11/site-packages/colorspacious/ciecam02.py", line 215, in XYZ100_to_CIECAM02
    / (tmp + (h_i[i + 1] - hprime) / e_i[i + 1]))
              ~~~^^^^^^^
IndexError: index 5 is out of bounds for axis 0 with size 5
```

**Comment by mfisher87** [comment]
Just got done testing at `65b657f` (before the pile of recent changes) and both symptoms reproduce there as well. I'll add this to the list of pre-release tasks, just going to focus on Qt6 for now.

**Comment by mfisher87** [comment]
This was me being dumb. I forgot that this colormap uses Bezier splines. I didn't actually do what it says in the README.
